# Generated by Django 4.2.4 on 2023-08-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galery", "0002_fotografia_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=False),
        ),
    ]
