# Generated by Django 4.2.4 on 2023-08-23 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galery", "0003_fotografia_publicada"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="data_fotografia",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
